name: autofetch

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * 12,1,2,3 2,3,4'
  push:
    paths:
      - '.github/workflows/autofetch.yml'
      - 'usaco_util.ts'
      - 'run.sh'
      - 'push.sh'

jobs:
  scrape_usaco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run auto updates
        run: |
          npm ci 
          source run.sh || source push.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Ping usaco-guide
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: ${{ github.repository_owner }},
              repo: 'usaco-guide',
              workflow_id: 'update-usaco.yml',
              ref: 'algolia',
            })
    
