name: propagate

on:
  push:
    paths:
      - 'problems.json'

jobs:
  propagate:
    runs-on: ubuntu-latest
    steps:
      - name: Ping usaco guide
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: devo1ution,
              repo: usaco-guide,
              workflow_id: 'update-usaco.yml',
              ref: 'algolia',
            })
  