on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * 12,1,2,3 2,3,4'
  push:
    paths:
      - '.github/workflows/update_usaco.yml'
      - 'run.sh'
      - 'create_pr.sh'

jobs:
  scrape_usaco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run auto updates
        run: |
          git branch auto
          git checkout auto
          npm ci 
          source run.sh || source create_pr.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
    